### ISSUE TITLE
firefox-bookmarks flatten --filename error.

### ISSUE THREAD

**Issue by kernel52** [twolfson/firefox-bookmarks#3]
Hi and thanks for this nice tool you developed.
I get the following error while trying the cli option on windows. 

Is it an empty folder maybe? 

Thanks a lot,
Nikolas

`C:\Users\user\AppData\Roaming\npm\node_modules\firefox-bookmarks\lib\firefox-bookmarks.js:35
  var bookmarkFolders = bookmarkMenu.children;
                                     ^

TypeError: Cannot read property 'children' of undefined
    at Function.BookmarkCollection.parse (C:\Users\user\AppData\Roaming\npm\node_modules\firefox-bookmarks\lib\firefox-bookmarks.js:35:38)
    at new BookmarkCollection (C:\Users\user\AppData\Roaming\npm\node_modules\firefox-bookmarks\lib\firefox-bookmarks.js:10:38)
    at C:\Users\user\AppData\Roaming\npm\node_modules\firefox-bookmarks\lib\cli.js:63:26
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
`

**Comment by twolfson** [comment]
Hmm, I don't know. Firefox may have changed their bookmark structure since this was implemented. I don't have much free time at the moment. Would you mind exploring this?

Marking as "help wanted" for now

**Comment by kernel52** [comment]
Thanks for replying. I sure know how things can be busy. 

Sure thing! I would be interested to give it a try. 
Any tips you think they can help me find my way around?  

Nikolas

**Comment by twolfson** [comment]
Hmm, probably look at the structure of JSON and see if aligns with the script's expectations
